name: tf-handwriting
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - opencv-python-headless
      - numpy
      - pandas
      - matplotlib
      - tensorflow[and-cuda]
      - keras
      
